# Base image
FROM python:3.9-slim

# Set the working directory to /app
WORKDIR /app

# Copy the requirements.txt file to the working directory
COPY requirements.txt .

# Install the Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the Flask app (server.py) to the working directory
COPY server.py .

# Expose port 8080 (or any port) for the Flask app
EXPOSE 8080

# Set the command to run the Flask app
CMD ["python", "server.py"]