version: '3.8'

services:
  training:
    build:
      context: .
      dockerfile: Dockerfile.train
    volumes:
      - model_storage:/app/models
    command: ["python", "train.py"]
    restart: on-failure

  inference:
    build:
      context: .
      dockerfile: Dockerfile.infer
    volumes:
      - model_storage:/app/models
    ports:
      - "8080:8080"
    depends_on:
      - training
    command: /bin/sh -c "sleep 10 && python server.py"

volumes:
  model_storage:
    driver: local