# Base image
FROM python:3.9-slim

# Set the working directory to /app
WORKDIR /app

RUN mkdir -p /app/models && chmod -R 777 /app/models

# Copy the requirements.txt file to the working directory
COPY requirements.txt .

# Install the Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the training script (train.py) to the working directory
COPY train.py .

# Run the training script that generates the model
CMD ["python", "train.py"]